### ISSUE TITLE
Página cursos Portal TIM Tec

### ISSUE THREAD

**Issue by Nathlis** [institutotim/portal-timtec#1]
A página de cursos não está carregando, no WordPress está tudo publicado (25 cursos).

![todos os cursos portal tim tec](https://user-images.githubusercontent.com/18741130/28384024-8cd05c70-6c99-11e7-95c8-227033d4cdad.png)

![courses portal tim tec wordpress](https://user-images.githubusercontent.com/18741130/28384033-925f368e-6c99-11e7-8251-b5e43c59ba4e.png)

**Comment by GustavoVS** [comment]
Corrigido problema de memória no servidor.
